version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: customers
      - name: orders
  - name: stripe
    database: dbt-tutorial
    schema: stripe
    tables:
      - name: payment
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}